### PR TITLE
Removed unnecessary "WpfScreenHelper" library

### PR DESCRIPTION
**Pull request by DocBrown101**

### CODE REVIEW

**Comment by TheJoeFin** [comment]
@DocBrown101 do you know why I added WPF Screen Helpers to begin with?

**Comment by DocBrown101** [comment]
No, I don't know, but the only reason for the WpfScreenHelper is that you don't have a dependency on Windows Forms, but this is already included in the project.

**Comment by TheJoeFin** [comment]
@DocBrown101 the plan is to remove a dependency on WinForms. However, I originally used this package to test if the WPF Screen would handle the UI scaling better. This issue #228 and similar issues on the PowerToys Text Extractor repo highlight that the way WinForms iterates through the screens, places an overlay, and captures the pixels of that screen is not perfect.

I probably won't be accepting this PR unless you have a specific reason (other than reducing dependencies) to remove this package. If you want to help with the work to remove a dependency on WinForms I would appreciate the help!

**Comment by DocBrown101** [comment]
It's ok for me, but I don't understand what's so bad about the official WinForms dependency?

Microsoft made it clear a long time ago that WPF will **never** catch up with Winforms in the sense of functional equality, so there may always be missing functions in the future.

So why use an outdated WpfScreenHelper lib, what problem does this solve?

**Pull request merged**
