### PR TITLE
v4.7

### PR DESCRIPTION
**Pull request by TheJoeFin**
Brings in to major features

- Searching history in the Quick Simple Lookup
    - Find and open previous Edit Text Windows or Grab Frames
    - Can be disabled for previous behavior
- Post grab actions
    - Can fix GUIDs
    - Try to insert
    - Trim lines
    - Remove duplicate lines
    - Default web search (configurable in Settings)

### CODE REVIEW

**Comment by vivadavid** [comment]
Hi!

Is there a place to learn how the new post grab actions work? For example, I don't know what 'Can fix GUIDs' does.

Thanks.

**Comment by TheJoeFin** [comment]
@vivadavid I opened a new issue to give better tooltips for the post grab actions, but fix GUIDs will try to correct common errors to characters which would be valid in a GUID which is only hexadecimal.

**Comment by vivadavid** [comment]
My problem is that I don't even know what GUID means. I tried to Google it, but I couldn't understand the information and connect it to OCR.

Tooltips would certainly be appreciated. Thanks.

**Comment by TheJoeFin** [comment]
https://en.wikipedia.org/wiki/Universally_unique_identifier?wprov=sfti1

They represent something which is tedious to copy manually so a good candidate for OCR, but they need to be exactly correct. So that function does some correcting based on possible values for each character.

**Comment by vivadavid** [comment]
> https://en.wikipedia.org/wiki/Universally_unique_identifier?wprov=sfti1
> 
> They represent something which is tedious to copy manually so a good candidate for OCR, but they need to be exactly correct. So that function does some correcting based on possible values for each character.

Thanks for the clarification.

**Pull request merged**
