### PR TITLE
Drag selection

### PR DESCRIPTION
**Pull request by AntonyCorbett**
Fix drag selection in GrabFrame (similar to PR 89 for full-screen).
Constrain mouse cursor during drag selection (both full-screen and grab frame).
Refactored to remove duplicate drawing of selection rectangle.

### CODE REVIEW

**Comment by TheJoeFin** [comment]
When testing this PR my mouse got stuck in a smaller area than the Fullscreen Grab or the Grab Frame. I suspect it has to do with my display scaling set to 150% on a 4k screen.

**Comment by AntonyCorbett** [comment]
> When testing this PR my mouse got stuck in a smaller area than the Fullscreen Grab or the Grab Frame. I suspect it has to do with my display scaling set to 150% on a 4k screen.

Fixed now

**Comment by TheJoeFin** [comment]
Because of the changes in #91 this PR now has some conflicts.

**Comment by AntonyCorbett** [comment]
Replaced with PR #92

**Pull request closed without merging**
