### PR TITLE
Add Functionality to Include Text-Grab in System PATH and Build Process Enhancements

### PR DESCRIPTION
**Pull request by tejaschaudhari131**
This PR introduces the following changes to the Text-Grab project:

1. Feature: Add Text-Grab to System PATH
Added a new feature that allows the Text-Grab executable to be automatically added to the system PATH during the build process.
Users can now launch Text-Grab directly from any terminal or command prompt by typing TextGrab, without needing to specify the full path to the executable.
The system PATH is updated by appending the executable's location, ensuring that Text-Grab is accessible globally across the system.
2. Build Process Enhancements
Modified the build-x64.ps1 script to build both self-contained and non-self-contained versions of Text-Grab.
Cleaned up the build directory before generating new builds to ensure no old artifacts interfere with the new build.
Both builds are archived into respective .zip files for easy distribution:
Non-Self-Contained Build: Archived as Text-Grab-YYYY-MM-DD.zip.
Self-Contained Build: Archived as Text-Grab-Self-Contained-YYYY-MM-DD.zip.

Related Issues:
Issue #471: [Add Text Grab to PATH](https://github.com/TheJoeFin/Text-Grab/issues/471)

### CODE REVIEW

**Comment by tejaschaudhari131** [comment]
Issue #471: [Add Text Grab to PATH](https://github.com/TheJoeFin/Text-Grab/issues/471)

**Comment by TheJoeFin** [comment]
This is great! Thank you for the pull request! I'll review this today.

**Comment by TheJoeFin** [comment]
@tejaschaudhari131 just checking in with this PR. This only adds Text Grab to the PATH when you run this PowerShell script. Typical users of the app will not have an option to add Text Grab to path, right?

I think #471 is related to having a button in Settings or the About Window enabling a simple and quick way to add Text Grab to the path.

**Comment by tejaschaudhari131** [comment]
Hi @TheJoeFin,

Thank you for your feedback on the PR! You're absolutely right; my initial implementation was more developer-centric and might not be as accessible for typical users.

I like the idea of integrating this feature directly into the GUI for ease of use. I propose adding a button in the Settings or About Window that lets users add Text Grab to the system PATH with just a simple click. This approach would make it more user-friendly and accessible to everyone.

I'll work on implementing this and will update the pull request with the new changes soon. Let me know if there are any specific considerations you'd like me to keep in mind while making these adjustments.

Thanks!

**Comment by TheJoeFin** [comment]
Sounds good. Side note: please base your branch off the `dev` branch and not `main`

**Pull request closed without merging**
