### PR TITLE
migrate to .net 5 with x86 and x64 support and build scripts

### PR DESCRIPTION
**Pull request by DocBrown101**
I hope you like it. I had problems getting it to work with .net core 3. Now everything runs much smoother.

### CODE REVIEW

**Comment by TheJoeFin** [comment]
Thanks for the PR updating to .NET 5 and making build scripts. The changes to `Text-Grab.csproj` break images from loading in the `FirstRunWindow`. You can open this Window from the `Edit Text Window` Help > About

**Comment by DocBrown101** [comment]
Ok, I didn't know that was necessary. I have restored it!

**Comment by TheJoeFin** [comment]
The build scripts complete, but the generated EXE does not properly load images. Not sure how to fix that.

**Comment by DocBrown101** [comment]
I can take a closer look tonight. How exactly do you start the exe file?

**Comment by TheJoeFin** [comment]
After I run the build script an exe is generated in a bld directory, double clicking on the exe is what I'm referring to when I see the app run without the images

**Comment by DocBrown101** [comment]
Now I get it! The images are now displayed!

**Comment by TheJoeFin** [comment]
Works good for me too!

**Pull request merged**
